parameters:

services:
    kuma_tagging.tag_manager:
        class: Kunstmaan\TaggingBundle\Entity\TagManager
        arguments: ["@doctrine.orm.entity_manager", "Kunstmaan\TaggingBundle\Entity\Tag", "Kunstmaan\TaggingBundle\Entity\Tagging"]

    kuma_tagging.listener:
        class: Kunstmaan\TaggingBundle\Listener\TagsListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: kernel.event_listener, event: nnode.postEdit, method: postPageEdit }
            - { name: kernel.event_listener, event: media.postEdit, method: postMediaEdit }
            - { name: kernel.event_listener, event: media.postCreate, method: postMediaCreate }

    kuma_tagging.menu.adaptor:
        class: Kunstmaan\TaggingBundle\Helper\Menu\TagMenuAdaptor
        tags:
          -  { name: kunstmaan_admin.menu.adaptor }

    form.type.tags:
        class: Kunstmaan\TaggingBundle\Form\TagsAdminType
        arguments: ["@kuma_tagging.tag_manager"]
        tags:
            - { name: form.type, alias: tags }
